Feature/mass payout revamp
Multisafe/multisafe-frontend-app pull request #54
Opened 2021-11-19 11:36 UTC by roheat

2021-11-21 22:38 UTC, DimaKoshevoy requested changes

2021-11-21 22:38 UTC, DimaKoshevoy commented on src/components/NewTransfer/SelectFromTeam.jsx
> +                checked={isCheckedAll}
isCheckedAll can be just a 'checked' array .every check here, instead of storing as state value and having to manage it

2021-11-21 22:38 UTC, DimaKoshevoy commented on src/components/Payments/styles/SearchNameInput.ts
> +import styled from "styled-components";
note to self :) should be styled-components/macro

2021-11-21 22:38 UTC, DimaKoshevoy commented on src/components/TransactionDetails/FlexibleMassPayoutDetails.tsx
> +interface Receiver {
let's use type everywhere for now

2021-11-21 22:38 UTC, DimaKoshevoy commented on src/components/TransactionDetails/FlexibleMassPayoutDetails.tsx
> +interface Receivers extends Array<Receiver> {}
extend doesn't fit here, this type can just be `Array<PaidTeammate>` or as separate type `type Receivers = Array<Receiver>` or `type Receivers = Receiver[]`

2021-11-21 22:38 UTC, DimaKoshevoy commented on src/components/TransactionDetails/FlexibleMassPayoutDetails.tsx
> +  paidTeammates: PaidTeammates;
same as above, this can be just `Array<PaidTeammate>` here

2021-11-21 22:38 UTC, DimaKoshevoy commented on src/components/TransactionDetails/TransactionDescription.tsx
> +  decryptedDescription: String;
this not a typescript `string` primitive but a native javascript String object interface

2021-11-21 22:38 UTC, DimaKoshevoy commented on src/components/common/Accordion/index.tsx
> +type IToggleContext = {
no need to start type name with `I`

2021-11-27 10:19 UTC, roheat commented on src/components/NewTransfer/NestedReceivers.jsx
> +          isDisabled: 1,
react hook form converts bool to string. so false becomes "false" - so i went with 0/1

2021-11-27 10:46 UTC, roheat commented on src/components/NewTransfer/SelectFromTeam.jsx
> +                checked={isCheckedAll}
noted, will do this refactor in next release

2021-11-27 10:47 UTC, roheat commented on src/components/NewTransfer/NestedReceivers.jsx
> +  k,
renaming to `NestedReceiver`

2021-11-27 14:32 UTC, DimaKoshevoy commented on src/components/NewTransfer/NestedReceivers.jsx
> +  k,
I meant the `k` field on line 28

2021-11-27 14:34 UTC, DimaKoshevoy commented on src/components/NewTransfer/NestedReceivers.jsx
> +          isDisabled: 1,
not a fun of react hook form requiring this kinds of "hoop jumping", let's discuss it later on v2 refactoring

2021-11-27 14:37 UTC, DimaKoshevoy commented on src/components/NewTransfer/SelectFromTeam.jsx
> +                checked={isCheckedAll}
+

2021-12-01 10:00 UTC, merged